commerce_invoice.commerce_invoice_type.*:
  type: commerce_config_entity_bundle
  label: 'Invoice type'
  mapping:
    numberPattern:
      type: string
      label: 'The number pattern'
    logo:
      type: string
      label: 'The logo file UUID'
    footerText:
      type: text
      label: 'Footer text'
    dueDays:
      type: integer
      label: 'Due days'
    paymentTerms:
      type: text
      label: 'Payment terms'
    workflow:
      type: string
      label: 'Workflow'

commerce_order.commerce_order_type.*.third_party.commerce_invoice:
  type: mapping
  label: 'Invoice settings'
  mapping:
    invoice_type:
      type: string
      label: 'Invoice type'
    order_placed_generation:
      type: boolean
      label: 'Order placed generation'
