commerce_invoice.commerce_invoice_type.*:
  type: commerce_config_entity_bundle
  label: 'Invoice type'
  mapping:
    workflow:
      type: string
      label: 'Workflow'

commerce_invoice.commerce_invoice_item_type.*:
  type: commerce_config_entity_bundle
  label: 'Invoice item type'
