commerce_invoice.commerce_invoice_type.*:
  type: commerce_config_entity_bundle
  label: 'Invoice type'
  mapping:
    footerText:
      type: text
      label: 'Footer text'
    paymentTerms:
      type: text
      label: 'Payment terms'
    numberGenerator:
      type: string
      label: 'Number generator'
    numberGeneratorConfiguration:
      type: commerce_invoice.commerce_number_generator.plugin.[%parent.numberGenerator]
    workflow:
      type: string
      label: 'Workflow'

commerce_order.commerce_order_type.*.third_party.commerce_invoice:
  type: mapping
  label: 'Invoice settings'
  mapping:
    invoice_type:
      type: string
      label: 'Invoice type'

commerce_invoice.commerce_number_generator.plugin.*:
  type: mapping
  mapping:
    pattern:
      type: string
      label: 'Pattern'
    padding:
      type: integer
      label: 'Padding'

commerce_invoice.commerce_number_generator.plugin.infinite:
  type: mapping
  mapping:
    pattern:
      type: string
      label: 'Pattern'
    padding:
      type: integer
      label: 'Padding'
    initialNumber:
      type: integer
      label: 'Initial invoice number'
