commerce_invoice.commerce_invoice_type.*:
  type: commerce_config_entity_bundle
  label: 'Invoice type'
  mapping:
    workflow:
      type: string
      label: 'Workflow'

commerce_order.commerce_order_type.*.third_party.commerce_invoice:
  type: mapping
  label: 'Invoice settings'
  mapping:
    invoice_type:
      type: string
      label: 'Invoice type'
